<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mechanism.proto

namespace Mechanism;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>mechanism.Request</code>
 */
class Request extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string domainName = 1;</code>
     */
    private $domainName = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $domainName
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Mechanism::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string domainName = 1;</code>
     * @return string
     */
    public function getDomainName()
    {
        return $this->domainName;
    }

    /**
     * Generated from protobuf field <code>string domainName = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setDomainName($var)
    {
        GPBUtil::checkString($var, True);
        $this->domainName = $var;

        return $this;
    }

}

