<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto

namespace GPBMetadata;

class Auth
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab3020a0a617574682e70726f746f12046175746822380a075265717565" .
            "7374120e0a06757365726964180120012803120e0a066f70656e69641802" .
            "20012809120d0a05746f6b656e18032001280922340a08526573706f6e73" .
            "65120c0a04636f6465180120012805120b0a036d7367180220012809120d" .
            "0a05746f6b656e18032001280932a6010a044175746812320a0f4d616b65" .
            "416363657373546f6b656e120d2e617574682e526571756573741a0e2e61" .
            "7574682e526573706f6e7365220012350a1244656c557365724163636573" .
            "73546f6b656e120d2e617574682e526571756573741a0e2e617574682e52" .
            "6573706f6e7365220012330a10436865636b416363657373546f6b656e12" .
            "0d2e617574682e526571756573741a0e2e617574682e526573706f6e7365" .
            "2200620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

