<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: courseadmin.proto

namespace GPBMetadata;

class Courseadmin
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aff010a11636f7572736561646d696e2e70726f746f120b636f75727365" .
            "61646d696e22510a075265717565737412140a0c6d656368616e69736d5f" .
            "6964180120012803120c0a0470616765180220012805120d0a056c696d69" .
            "7418032001280512130a0b7365617263685f6e616d651804200128092237" .
            "0a08526573706f6e7365120f0a0773756363657373180120012809120c0a" .
            "04636f6465180220012803120c0a046461746118032001280932490a0b43" .
            "6f7572736561646d696e123a0a0941646d696e4c69737412142e636f7572" .
            "736561646d696e2e526571756573741a152e636f7572736561646d696e2e" .
            "526573706f6e73652200620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

