<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: course.proto

namespace GPBMetadata;

class Course
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ad7020a0c636f757273652e70726f746f1206636f75727365221a0a0a63" .
            "6f75727365496e666f120c0a046461746118012001280922220a0d676574" .
            "526571756573744f6e6512110a09636f757273655f696418012001280922" .
            "260a0e676574526571756573744c69737412140a0c6d656368616e69736d" .
            "5f6964180120012803223d0a0e636f75727365526573706f6e7365120f0a" .
            "0773756363657373180120012809120c0a0464617461180220012809120c" .
            "0a04636f6465180320012805328f010a0d436f7572736553657276696365" .
            "123d0a0a47657443757272526f7712152e636f757273652e676574526571" .
            "756573744f6e651a162e636f757273652e636f75727365526573706f6e73" .
            "652200123f0a0b476574437572724c69737412162e636f757273652e6765" .
            "74526571756573744c6973741a162e636f757273652e636f757273655265" .
            "73706f6e73652200620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

