<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: login.proto

namespace GPBMetadata;

class Login
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0af0010a0b6c6f67696e2e70726f746f12056c6f67696e222c0a07526571" .
            "7565737412120a0a646f6d61696e4e616d65180120012809120d0a057363" .
            "656e6518022001280322370a08526573706f6e7365120f0a077375636365" .
            "7373180120012809120c0a04636f6465180220012803120c0a0464617461" .
            "180320012809326b0a054c6f67696e12310a0c4765744c6f67696e436f64" .
            "65120e2e6c6f67696e2e526571756573741a0f2e6c6f67696e2e52657370" .
            "6f6e73652200122f0a0a436865636b4c6f67696e120e2e6c6f67696e2e52" .
            "6571756573741a0f2e6c6f67696e2e526573706f6e73652200620670726f" .
            "746f33"
        ));

        static::$is_initialized = true;
    }
}

