<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: login.proto

namespace GPBMetadata;

class Login
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab0010a0b6c6f67696e2e70726f746f12056c6f67696e221d0a07526571" .
            "7565737412120a0a646f6d61696e4e616d6518012001280922370a085265" .
            "73706f6e7365120f0a0773756363657373180120012809120c0a04636f64" .
            "65180220012803120c0a0464617461180320012809323a0a054c6f67696e" .
            "12310a0c4765744c6f67696e436f6465120e2e6c6f67696e2e5265717565" .
            "73741a0f2e6c6f67696e2e526573706f6e73652200620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

