<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: login.proto

namespace GPBMetadata;

class Login
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a82030a0b6c6f67696e2e70726f746f12056c6f67696e224d0a07526571" .
            "7565737412120a0a646f6d61696e4e616d65180120012809120d0a057363" .
            "656e65180220012803120d0a0570686f6e6518032001280912100a087061" .
            "7373776f726418042001280922770a08526573706f6e7365120f0a077375" .
            "6363657373180120012809120c0a04636f6465180220012803120c0a0464" .
            "61746118032001280912120a0a6d656368616e6973616d18042001280912" .
            "0c0a0475736572180520012809120d0a0561646d696e180620012809120d" .
            "0a05746f6b656e180720012809329b010a054c6f67696e12310a0c476574" .
            "4c6f67696e436f6465120e2e6c6f67696e2e526571756573741a0f2e6c6f" .
            "67696e2e526573706f6e73652200122f0a0a436865636b4c6f67696e120e" .
            "2e6c6f67696e2e526571756573741a0f2e6c6f67696e2e526573706f6e73" .
            "652200122e0a094e616d654c6f67696e120e2e6c6f67696e2e5265717565" .
            "73741a0f2e6c6f67696e2e526573706f6e73652200620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

