<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mechanism.proto

namespace GPBMetadata;

class Mechanism
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ad9020a0f6d656368616e69736d2e70726f746f12096d656368616e6973" .
            "6d22b0010a0752657175657374120a0a02696418012001280312170a0f69" .
            "735f68656164717561727465727318022001280512150a0d617574686f72" .
            "697a65725f696418032001280312130a0b69735f706167696e6174651804" .
            "20012805120d0a056c696d6974180520012805120c0a0470616765180620" .
            "012805120e0a0670726f5f6964180720012803120f0a07636974795f6964" .
            "18082001280312160a0e6d656368616e69736d5f6e616d65180920012809" .
            "22370a08526573706f6e7365120f0a077375636365737318012001280912" .
            "0c0a04636f6465180220012803120c0a046461746118032001280932470a" .
            "094d656368616e69736d123a0a0d4d656368616e69736d4c69737412122e" .
            "6d656368616e69736d2e526571756573741a132e6d656368616e69736d2e" .
            "526573706f6e73652200620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

