<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mechanism.proto

namespace GPBMetadata;

class Mechanism
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0adc010a0f6d656368616e69736d2e70726f746f12096d656368616e6973" .
            "6d22160a074d657373616765120b0a03736179180120012809221d0a0752" .
            "65717565737412120a0a646f6d61696e4e616d6518012001280922370a08" .
            "526573706f6e7365120f0a0773756363657373180120012809120c0a0463" .
            "6f6465180220012803120c0a046461746118032001280932460a094d6563" .
            "68616e69736d12390a0c4765744c6f67696e436f646512122e6d65636861" .
            "6e69736d2e526571756573741a132e6d656368616e69736d2e526573706f" .
            "6e73652200620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

