<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: users.proto

namespace GPBMetadata;

class Users
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a97020a0b75736572732e70726f746f1205757365727322350a09557365" .
            "7273696e666f120a0a026964180120012803120c0a046e616d6518022001" .
            "2809120e0a066f70656e696418032001280922220a054572726f72120c0a" .
            "04636f6465180120012805120b0a036d736718022001280922270a075265" .
            "7175657374120e0a06757365726964180120012803120c0a046e616d6518" .
            "0220012809223c0a08526573706f6e7365120f0a07737563636573731801" .
            "20012809120c0a04636f646518022001280312110a095573657273696e66" .
            "6f18032001280932370a055573657273122e0a0947657455736572496412" .
            "0e2e75736572732e526571756573741a0f2e75736572732e526573706f6e" .
            "73652200620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

