<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: users.proto

namespace GPBMetadata;

class Users
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a99020a0b75736572732e70726f746f1205757365727322250a09557365" .
            "7273696e666f120a0a026964180120012803120c0a046e616d6518022001" .
            "280922220a054572726f72120c0a04636f6465180120012805120b0a036d" .
            "736718022001280922270a0752657175657374120e0a0675736572696418" .
            "0120012803120c0a046e616d65180220012809224e0a08526573706f6e73" .
            "65120f0a0773756363657373180120012809120c0a04636f646518022001" .
            "280312230a097573657273696e666f18032003280b32102e75736572732e" .
            "5573657273696e666f32370a055573657273122e0a094765745573657249" .
            "64120e2e75736572732e526571756573741a0f2e75736572732e52657370" .
            "6f6e73652200620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

