<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: login.proto

namespace Login;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>login.Response</code>
 */
class Response extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string success = 1;</code>
     */
    private $success = '';
    /**
     * Generated from protobuf field <code>int64 code = 2;</code>
     */
    private $code = 0;
    /**
     * Generated from protobuf field <code>string data = 3;</code>
     */
    private $data = '';
    /**
     * Generated from protobuf field <code>string mechanisam = 4;</code>
     */
    private $mechanisam = '';
    /**
     * Generated from protobuf field <code>string user = 5;</code>
     */
    private $user = '';
    /**
     * Generated from protobuf field <code>string admin = 6;</code>
     */
    private $admin = '';
    /**
     * Generated from protobuf field <code>string token = 7;</code>
     */
    private $token = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $success
     *     @type int|string $code
     *     @type string $data
     *     @type string $mechanisam
     *     @type string $user
     *     @type string $admin
     *     @type string $token
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Login::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string success = 1;</code>
     * @return string
     */
    public function getSuccess()
    {
        return $this->success;
    }

    /**
     * Generated from protobuf field <code>string success = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSuccess($var)
    {
        GPBUtil::checkString($var, True);
        $this->success = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 code = 2;</code>
     * @return int|string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Generated from protobuf field <code>int64 code = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkInt64($var);
        $this->code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string data = 3;</code>
     * @return string
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * Generated from protobuf field <code>string data = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkString($var, True);
        $this->data = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string mechanisam = 4;</code>
     * @return string
     */
    public function getMechanisam()
    {
        return $this->mechanisam;
    }

    /**
     * Generated from protobuf field <code>string mechanisam = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setMechanisam($var)
    {
        GPBUtil::checkString($var, True);
        $this->mechanisam = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string user = 5;</code>
     * @return string
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Generated from protobuf field <code>string user = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setUser($var)
    {
        GPBUtil::checkString($var, True);
        $this->user = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string admin = 6;</code>
     * @return string
     */
    public function getAdmin()
    {
        return $this->admin;
    }

    /**
     * Generated from protobuf field <code>string admin = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setAdmin($var)
    {
        GPBUtil::checkString($var, True);
        $this->admin = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string token = 7;</code>
     * @return string
     */
    public function getToken()
    {
        return $this->token;
    }

    /**
     * Generated from protobuf field <code>string token = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->token = $var;

        return $this;
    }

}

