<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: users.proto

namespace Users;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>users.Response</code>
 */
class Response extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string success = 1;</code>
     */
    private $success = '';
    /**
     * Generated from protobuf field <code>int64 code = 2;</code>
     */
    private $code = 0;
    /**
     * Generated from protobuf field <code>string Usersinfo = 3;</code>
     */
    private $Usersinfo = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $success
     *     @type int|string $code
     *     @type string $Usersinfo
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Users::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string success = 1;</code>
     * @return string
     */
    public function getSuccess()
    {
        return $this->success;
    }

    /**
     * Generated from protobuf field <code>string success = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSuccess($var)
    {
        GPBUtil::checkString($var, True);
        $this->success = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 code = 2;</code>
     * @return int|string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Generated from protobuf field <code>int64 code = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkInt64($var);
        $this->code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Usersinfo = 3;</code>
     * @return string
     */
    public function getUsersinfo()
    {
        return $this->Usersinfo;
    }

    /**
     * Generated from protobuf field <code>string Usersinfo = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setUsersinfo($var)
    {
        GPBUtil::checkString($var, True);
        $this->Usersinfo = $var;

        return $this;
    }

}

