<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bluesystem.proto

namespace Bluesystem;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *系统设置修改参数定义
 *
 * Generated from protobuf message <code>bluesystem.SetSettingRequest</code>
 */
class SetSettingRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    private $id = '';
    /**
     * Generated from protobuf field <code>bool flag = 2;</code>
     */
    private $flag = false;
    /**
     * Generated from protobuf field <code>string loginimg = 3;</code>
     */
    private $loginimg = '';
    /**
     * Generated from protobuf field <code>string logo = 4;</code>
     */
    private $logo = '';
    /**
     * Generated from protobuf field <code>string name = 5;</code>
     */
    private $name = '';
    /**
     * Generated from protobuf field <code>string titlecolor = 6;</code>
     */
    private $titlecolor = '';
    /**
     * Generated from protobuf field <code>.bluesystem.titlefontData titlefont = 7;</code>
     */
    private $titlefont = null;
    /**
     * Generated from protobuf field <code>int32 alarmlog = 8;</code>
     */
    private $alarmlog = 0;
    /**
     * Generated from protobuf field <code>int32 equipmentlog = 9;</code>
     */
    private $equipmentlog = 0;
    /**
     * Generated from protobuf field <code>int32 operationlog = 10;</code>
     */
    private $operationlog = 0;
    /**
     * Generated from protobuf field <code>int32 configlog = 11;</code>
     */
    private $configlog = 0;
    /**
     * Generated from protobuf field <code>string transport = 12;</code>
     */
    private $transport = '';
    /**
     * Generated from protobuf field <code>string picture = 13;</code>
     */
    private $picture = '';
    /**
     * Generated from protobuf field <code>string screenshot = 14;</code>
     */
    private $screenshot = '';
    /**
     * Generated from protobuf field <code>string videotape = 15;</code>
     */
    private $videotape = '';
    /**
     * Generated from protobuf field <code>bool serverAuth = 16;</code>
     */
    private $serverAuth = false;
    /**
     * Generated from protobuf field <code>int32 smtpPort = 17;</code>
     */
    private $smtpPort = 0;
    /**
     * Generated from protobuf field <code>string sendName = 18;</code>
     */
    private $sendName = '';
    /**
     * Generated from protobuf field <code>string email = 19;</code>
     */
    private $email = '';
    /**
     * Generated from protobuf field <code>bool ssl = 20;</code>
     */
    private $ssl = false;
    /**
     * Generated from protobuf field <code>string smtpServer = 21;</code>
     */
    private $smtpServer = '';
    /**
     * Generated from protobuf field <code>string userName = 22;</code>
     */
    private $userName = '';
    /**
     * Generated from protobuf field <code>string password = 23;</code>
     */
    private $password = '';
    /**
     * Generated from protobuf field <code>string rtmp = 24;</code>
     */
    private $rtmp = '';
    /**
     * Generated from protobuf field <code>string storage = 25;</code>
     */
    private $storage = '';
    /**
     * Generated from protobuf field <code>int32 path = 26;</code>
     */
    private $path = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type bool $flag
     *     @type string $loginimg
     *     @type string $logo
     *     @type string $name
     *     @type string $titlecolor
     *     @type \Bluesystem\titlefontData $titlefont
     *     @type int $alarmlog
     *     @type int $equipmentlog
     *     @type int $operationlog
     *     @type int $configlog
     *     @type string $transport
     *     @type string $picture
     *     @type string $screenshot
     *     @type string $videotape
     *     @type bool $serverAuth
     *     @type int $smtpPort
     *     @type string $sendName
     *     @type string $email
     *     @type bool $ssl
     *     @type string $smtpServer
     *     @type string $userName
     *     @type string $password
     *     @type string $rtmp
     *     @type string $storage
     *     @type int $path
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Bluesystem::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool flag = 2;</code>
     * @return bool
     */
    public function getFlag()
    {
        return $this->flag;
    }

    /**
     * Generated from protobuf field <code>bool flag = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setFlag($var)
    {
        GPBUtil::checkBool($var);
        $this->flag = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string loginimg = 3;</code>
     * @return string
     */
    public function getLoginimg()
    {
        return $this->loginimg;
    }

    /**
     * Generated from protobuf field <code>string loginimg = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setLoginimg($var)
    {
        GPBUtil::checkString($var, True);
        $this->loginimg = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string logo = 4;</code>
     * @return string
     */
    public function getLogo()
    {
        return $this->logo;
    }

    /**
     * Generated from protobuf field <code>string logo = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setLogo($var)
    {
        GPBUtil::checkString($var, True);
        $this->logo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 5;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string titlecolor = 6;</code>
     * @return string
     */
    public function getTitlecolor()
    {
        return $this->titlecolor;
    }

    /**
     * Generated from protobuf field <code>string titlecolor = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setTitlecolor($var)
    {
        GPBUtil::checkString($var, True);
        $this->titlecolor = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.bluesystem.titlefontData titlefont = 7;</code>
     * @return \Bluesystem\titlefontData
     */
    public function getTitlefont()
    {
        return $this->titlefont;
    }

    /**
     * Generated from protobuf field <code>.bluesystem.titlefontData titlefont = 7;</code>
     * @param \Bluesystem\titlefontData $var
     * @return $this
     */
    public function setTitlefont($var)
    {
        GPBUtil::checkMessage($var, \Bluesystem\titlefontData::class);
        $this->titlefont = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 alarmlog = 8;</code>
     * @return int
     */
    public function getAlarmlog()
    {
        return $this->alarmlog;
    }

    /**
     * Generated from protobuf field <code>int32 alarmlog = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setAlarmlog($var)
    {
        GPBUtil::checkInt32($var);
        $this->alarmlog = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 equipmentlog = 9;</code>
     * @return int
     */
    public function getEquipmentlog()
    {
        return $this->equipmentlog;
    }

    /**
     * Generated from protobuf field <code>int32 equipmentlog = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setEquipmentlog($var)
    {
        GPBUtil::checkInt32($var);
        $this->equipmentlog = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 operationlog = 10;</code>
     * @return int
     */
    public function getOperationlog()
    {
        return $this->operationlog;
    }

    /**
     * Generated from protobuf field <code>int32 operationlog = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setOperationlog($var)
    {
        GPBUtil::checkInt32($var);
        $this->operationlog = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 configlog = 11;</code>
     * @return int
     */
    public function getConfiglog()
    {
        return $this->configlog;
    }

    /**
     * Generated from protobuf field <code>int32 configlog = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setConfiglog($var)
    {
        GPBUtil::checkInt32($var);
        $this->configlog = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string transport = 12;</code>
     * @return string
     */
    public function getTransport()
    {
        return $this->transport;
    }

    /**
     * Generated from protobuf field <code>string transport = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setTransport($var)
    {
        GPBUtil::checkString($var, True);
        $this->transport = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string picture = 13;</code>
     * @return string
     */
    public function getPicture()
    {
        return $this->picture;
    }

    /**
     * Generated from protobuf field <code>string picture = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setPicture($var)
    {
        GPBUtil::checkString($var, True);
        $this->picture = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string screenshot = 14;</code>
     * @return string
     */
    public function getScreenshot()
    {
        return $this->screenshot;
    }

    /**
     * Generated from protobuf field <code>string screenshot = 14;</code>
     * @param string $var
     * @return $this
     */
    public function setScreenshot($var)
    {
        GPBUtil::checkString($var, True);
        $this->screenshot = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string videotape = 15;</code>
     * @return string
     */
    public function getVideotape()
    {
        return $this->videotape;
    }

    /**
     * Generated from protobuf field <code>string videotape = 15;</code>
     * @param string $var
     * @return $this
     */
    public function setVideotape($var)
    {
        GPBUtil::checkString($var, True);
        $this->videotape = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool serverAuth = 16;</code>
     * @return bool
     */
    public function getServerAuth()
    {
        return $this->serverAuth;
    }

    /**
     * Generated from protobuf field <code>bool serverAuth = 16;</code>
     * @param bool $var
     * @return $this
     */
    public function setServerAuth($var)
    {
        GPBUtil::checkBool($var);
        $this->serverAuth = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 smtpPort = 17;</code>
     * @return int
     */
    public function getSmtpPort()
    {
        return $this->smtpPort;
    }

    /**
     * Generated from protobuf field <code>int32 smtpPort = 17;</code>
     * @param int $var
     * @return $this
     */
    public function setSmtpPort($var)
    {
        GPBUtil::checkInt32($var);
        $this->smtpPort = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string sendName = 18;</code>
     * @return string
     */
    public function getSendName()
    {
        return $this->sendName;
    }

    /**
     * Generated from protobuf field <code>string sendName = 18;</code>
     * @param string $var
     * @return $this
     */
    public function setSendName($var)
    {
        GPBUtil::checkString($var, True);
        $this->sendName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string email = 19;</code>
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Generated from protobuf field <code>string email = 19;</code>
     * @param string $var
     * @return $this
     */
    public function setEmail($var)
    {
        GPBUtil::checkString($var, True);
        $this->email = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool ssl = 20;</code>
     * @return bool
     */
    public function getSsl()
    {
        return $this->ssl;
    }

    /**
     * Generated from protobuf field <code>bool ssl = 20;</code>
     * @param bool $var
     * @return $this
     */
    public function setSsl($var)
    {
        GPBUtil::checkBool($var);
        $this->ssl = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string smtpServer = 21;</code>
     * @return string
     */
    public function getSmtpServer()
    {
        return $this->smtpServer;
    }

    /**
     * Generated from protobuf field <code>string smtpServer = 21;</code>
     * @param string $var
     * @return $this
     */
    public function setSmtpServer($var)
    {
        GPBUtil::checkString($var, True);
        $this->smtpServer = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string userName = 22;</code>
     * @return string
     */
    public function getUserName()
    {
        return $this->userName;
    }

    /**
     * Generated from protobuf field <code>string userName = 22;</code>
     * @param string $var
     * @return $this
     */
    public function setUserName($var)
    {
        GPBUtil::checkString($var, True);
        $this->userName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string password = 23;</code>
     * @return string
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * Generated from protobuf field <code>string password = 23;</code>
     * @param string $var
     * @return $this
     */
    public function setPassword($var)
    {
        GPBUtil::checkString($var, True);
        $this->password = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string rtmp = 24;</code>
     * @return string
     */
    public function getRtmp()
    {
        return $this->rtmp;
    }

    /**
     * Generated from protobuf field <code>string rtmp = 24;</code>
     * @param string $var
     * @return $this
     */
    public function setRtmp($var)
    {
        GPBUtil::checkString($var, True);
        $this->rtmp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string storage = 25;</code>
     * @return string
     */
    public function getStorage()
    {
        return $this->storage;
    }

    /**
     * Generated from protobuf field <code>string storage = 25;</code>
     * @param string $var
     * @return $this
     */
    public function setStorage($var)
    {
        GPBUtil::checkString($var, True);
        $this->storage = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 path = 26;</code>
     * @return int
     */
    public function getPath()
    {
        return $this->path;
    }

    /**
     * Generated from protobuf field <code>int32 path = 26;</code>
     * @param int $var
     * @return $this
     */
    public function setPath($var)
    {
        GPBUtil::checkInt32($var);
        $this->path = $var;

        return $this;
    }

}

