<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bluesystem.proto

namespace Bluesystem;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *系统设置修改参数定义
 *
 * Generated from protobuf message <code>bluesystem.SetSettingRequest</code>
 */
class SetSettingRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    private $id = '';
    /**
     * Generated from protobuf field <code>bool flag = 2;</code>
     */
    private $flag = false;
    /**
     * Generated from protobuf field <code>string loginimg = 3;</code>
     */
    private $loginimg = '';
    /**
     * Generated from protobuf field <code>string logo = 4;</code>
     */
    private $logo = '';
    /**
     * Generated from protobuf field <code>string name = 5;</code>
     */
    private $name = '';
    /**
     * Generated from protobuf field <code>string titlecolor = 6;</code>
     */
    private $titlecolor = '';
    /**
     * Generated from protobuf field <code>.bluesystem.titlefontData titlefont = 7;</code>
     */
    private $titlefont = null;
    /**
     * Generated from protobuf field <code>int32 alarmlog = 8;</code>
     */
    private $alarmlog = 0;
    /**
     * Generated from protobuf field <code>int32 equipmentlog = 9;</code>
     */
    private $equipmentlog = 0;
    /**
     * Generated from protobuf field <code>int32 operationlog = 10;</code>
     */
    private $operationlog = 0;
    /**
     * Generated from protobuf field <code>int32 configlog = 11;</code>
     */
    private $configlog = 0;
    /**
     * Generated from protobuf field <code>string transport = 12;</code>
     */
    private $transport = '';
    /**
     * Generated from protobuf field <code>string picture = 13;</code>
     */
    private $picture = '';
    /**
     * Generated from protobuf field <code>string screenshot = 14;</code>
     */
    private $screenshot = '';
    /**
     * Generated from protobuf field <code>string videotape = 15;</code>
     */
    private $videotape = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type bool $flag
     *     @type string $loginimg
     *     @type string $logo
     *     @type string $name
     *     @type string $titlecolor
     *     @type \Bluesystem\titlefontData $titlefont
     *     @type int $alarmlog
     *     @type int $equipmentlog
     *     @type int $operationlog
     *     @type int $configlog
     *     @type string $transport
     *     @type string $picture
     *     @type string $screenshot
     *     @type string $videotape
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Bluesystem::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool flag = 2;</code>
     * @return bool
     */
    public function getFlag()
    {
        return $this->flag;
    }

    /**
     * Generated from protobuf field <code>bool flag = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setFlag($var)
    {
        GPBUtil::checkBool($var);
        $this->flag = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string loginimg = 3;</code>
     * @return string
     */
    public function getLoginimg()
    {
        return $this->loginimg;
    }

    /**
     * Generated from protobuf field <code>string loginimg = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setLoginimg($var)
    {
        GPBUtil::checkString($var, True);
        $this->loginimg = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string logo = 4;</code>
     * @return string
     */
    public function getLogo()
    {
        return $this->logo;
    }

    /**
     * Generated from protobuf field <code>string logo = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setLogo($var)
    {
        GPBUtil::checkString($var, True);
        $this->logo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 5;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string titlecolor = 6;</code>
     * @return string
     */
    public function getTitlecolor()
    {
        return $this->titlecolor;
    }

    /**
     * Generated from protobuf field <code>string titlecolor = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setTitlecolor($var)
    {
        GPBUtil::checkString($var, True);
        $this->titlecolor = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.bluesystem.titlefontData titlefont = 7;</code>
     * @return \Bluesystem\titlefontData
     */
    public function getTitlefont()
    {
        return $this->titlefont;
    }

    /**
     * Generated from protobuf field <code>.bluesystem.titlefontData titlefont = 7;</code>
     * @param \Bluesystem\titlefontData $var
     * @return $this
     */
    public function setTitlefont($var)
    {
        GPBUtil::checkMessage($var, \Bluesystem\titlefontData::class);
        $this->titlefont = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 alarmlog = 8;</code>
     * @return int
     */
    public function getAlarmlog()
    {
        return $this->alarmlog;
    }

    /**
     * Generated from protobuf field <code>int32 alarmlog = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setAlarmlog($var)
    {
        GPBUtil::checkInt32($var);
        $this->alarmlog = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 equipmentlog = 9;</code>
     * @return int
     */
    public function getEquipmentlog()
    {
        return $this->equipmentlog;
    }

    /**
     * Generated from protobuf field <code>int32 equipmentlog = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setEquipmentlog($var)
    {
        GPBUtil::checkInt32($var);
        $this->equipmentlog = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 operationlog = 10;</code>
     * @return int
     */
    public function getOperationlog()
    {
        return $this->operationlog;
    }

    /**
     * Generated from protobuf field <code>int32 operationlog = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setOperationlog($var)
    {
        GPBUtil::checkInt32($var);
        $this->operationlog = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 configlog = 11;</code>
     * @return int
     */
    public function getConfiglog()
    {
        return $this->configlog;
    }

    /**
     * Generated from protobuf field <code>int32 configlog = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setConfiglog($var)
    {
        GPBUtil::checkInt32($var);
        $this->configlog = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string transport = 12;</code>
     * @return string
     */
    public function getTransport()
    {
        return $this->transport;
    }

    /**
     * Generated from protobuf field <code>string transport = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setTransport($var)
    {
        GPBUtil::checkString($var, True);
        $this->transport = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string picture = 13;</code>
     * @return string
     */
    public function getPicture()
    {
        return $this->picture;
    }

    /**
     * Generated from protobuf field <code>string picture = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setPicture($var)
    {
        GPBUtil::checkString($var, True);
        $this->picture = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string screenshot = 14;</code>
     * @return string
     */
    public function getScreenshot()
    {
        return $this->screenshot;
    }

    /**
     * Generated from protobuf field <code>string screenshot = 14;</code>
     * @param string $var
     * @return $this
     */
    public function setScreenshot($var)
    {
        GPBUtil::checkString($var, True);
        $this->screenshot = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string videotape = 15;</code>
     * @return string
     */
    public function getVideotape()
    {
        return $this->videotape;
    }

    /**
     * Generated from protobuf field <code>string videotape = 15;</code>
     * @param string $var
     * @return $this
     */
    public function setVideotape($var)
    {
        GPBUtil::checkString($var, True);
        $this->videotape = $var;

        return $this;
    }

}

