<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bluesystem.proto

namespace Bluesystem;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>bluesystem.titlefontData</code>
 */
class titlefontData extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string font = 1;</code>
     */
    private $font = '';
    /**
     * Generated from protobuf field <code>string size = 2;</code>
     */
    private $size = '';
    /**
     * Generated from protobuf field <code>string fontWeight = 3;</code>
     */
    private $fontWeight = '';
    /**
     * Generated from protobuf field <code>string fontColor = 4;</code>
     */
    private $fontColor = '';
    /**
     * Generated from protobuf field <code>string fontItalic = 5;</code>
     */
    private $fontItalic = '';
    /**
     * Generated from protobuf field <code>string fontRegular = 6;</code>
     */
    private $fontRegular = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $font
     *     @type string $size
     *     @type string $fontWeight
     *     @type string $fontColor
     *     @type string $fontItalic
     *     @type string $fontRegular
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Bluesystem::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string font = 1;</code>
     * @return string
     */
    public function getFont()
    {
        return $this->font;
    }

    /**
     * Generated from protobuf field <code>string font = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setFont($var)
    {
        GPBUtil::checkString($var, True);
        $this->font = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string size = 2;</code>
     * @return string
     */
    public function getSize()
    {
        return $this->size;
    }

    /**
     * Generated from protobuf field <code>string size = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSize($var)
    {
        GPBUtil::checkString($var, True);
        $this->size = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string fontWeight = 3;</code>
     * @return string
     */
    public function getFontWeight()
    {
        return $this->fontWeight;
    }

    /**
     * Generated from protobuf field <code>string fontWeight = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setFontWeight($var)
    {
        GPBUtil::checkString($var, True);
        $this->fontWeight = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string fontColor = 4;</code>
     * @return string
     */
    public function getFontColor()
    {
        return $this->fontColor;
    }

    /**
     * Generated from protobuf field <code>string fontColor = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setFontColor($var)
    {
        GPBUtil::checkString($var, True);
        $this->fontColor = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string fontItalic = 5;</code>
     * @return string
     */
    public function getFontItalic()
    {
        return $this->fontItalic;
    }

    /**
     * Generated from protobuf field <code>string fontItalic = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setFontItalic($var)
    {
        GPBUtil::checkString($var, True);
        $this->fontItalic = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string fontRegular = 6;</code>
     * @return string
     */
    public function getFontRegular()
    {
        return $this->fontRegular;
    }

    /**
     * Generated from protobuf field <code>string fontRegular = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setFontRegular($var)
    {
        GPBUtil::checkString($var, True);
        $this->fontRegular = $var;

        return $this;
    }

}

