<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: courseadmin.proto

namespace Courseadmin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>courseadmin.codeData</code>
 */
class codeData extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string url = 1;</code>
     */
    private $url = '';
    /**
     * Generated from protobuf field <code>int64 scene = 2;</code>
     */
    private $scene = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $url
     *     @type int|string $scene
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Courseadmin::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string url = 1;</code>
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * Generated from protobuf field <code>string url = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->url = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 scene = 2;</code>
     * @return int|string
     */
    public function getScene()
    {
        return $this->scene;
    }

    /**
     * Generated from protobuf field <code>int64 scene = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setScene($var)
    {
        GPBUtil::checkInt64($var);
        $this->scene = $var;

        return $this;
    }

}

