<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: courseadmin.proto

namespace Courseadmin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>courseadmin.Request</code>
 */
class Request extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 mechanism_id = 1;</code>
     */
    private $mechanism_id = 0;
    /**
     * Generated from protobuf field <code>int32 page = 2;</code>
     */
    private $page = 0;
    /**
     * Generated from protobuf field <code>int32 limit = 3;</code>
     */
    private $limit = 0;
    /**
     * Generated from protobuf field <code>string search_name = 4;</code>
     */
    private $search_name = '';
    /**
     * Generated from protobuf field <code>int32 number_people = 5;</code>
     */
    private $number_people = 0;
    /**
     * Generated from protobuf field <code>int64 user_id = 6;</code>
     */
    private $user_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $mechanism_id
     *     @type int $page
     *     @type int $limit
     *     @type string $search_name
     *     @type int $number_people
     *     @type int|string $user_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Courseadmin::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 mechanism_id = 1;</code>
     * @return int|string
     */
    public function getMechanismId()
    {
        return $this->mechanism_id;
    }

    /**
     * Generated from protobuf field <code>int64 mechanism_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMechanismId($var)
    {
        GPBUtil::checkInt64($var);
        $this->mechanism_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 page = 2;</code>
     * @return int
     */
    public function getPage()
    {
        return $this->page;
    }

    /**
     * Generated from protobuf field <code>int32 page = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setPage($var)
    {
        GPBUtil::checkInt32($var);
        $this->page = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 limit = 3;</code>
     * @return int
     */
    public function getLimit()
    {
        return $this->limit;
    }

    /**
     * Generated from protobuf field <code>int32 limit = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setLimit($var)
    {
        GPBUtil::checkInt32($var);
        $this->limit = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string search_name = 4;</code>
     * @return string
     */
    public function getSearchName()
    {
        return $this->search_name;
    }

    /**
     * Generated from protobuf field <code>string search_name = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setSearchName($var)
    {
        GPBUtil::checkString($var, True);
        $this->search_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 number_people = 5;</code>
     * @return int
     */
    public function getNumberPeople()
    {
        return $this->number_people;
    }

    /**
     * Generated from protobuf field <code>int32 number_people = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setNumberPeople($var)
    {
        GPBUtil::checkInt32($var);
        $this->number_people = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 user_id = 6;</code>
     * @return int|string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * Generated from protobuf field <code>int64 user_id = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkInt64($var);
        $this->user_id = $var;

        return $this;
    }

}

