<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: courseadmin.proto

namespace Courseadmin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>courseadmin.Response</code>
 */
class Response extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string success = 1;</code>
     */
    private $success = '';
    /**
     * Generated from protobuf field <code>int64 code = 2;</code>
     */
    private $code = 0;
    /**
     * Generated from protobuf field <code>string data = 3;</code>
     */
    private $data = '';
    /**
     * Generated from protobuf field <code>.courseadmin.codeData codedata = 4;</code>
     */
    private $codedata = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $success
     *     @type int|string $code
     *     @type string $data
     *     @type \Courseadmin\codeData $codedata
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Courseadmin::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string success = 1;</code>
     * @return string
     */
    public function getSuccess()
    {
        return $this->success;
    }

    /**
     * Generated from protobuf field <code>string success = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSuccess($var)
    {
        GPBUtil::checkString($var, True);
        $this->success = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 code = 2;</code>
     * @return int|string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Generated from protobuf field <code>int64 code = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkInt64($var);
        $this->code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string data = 3;</code>
     * @return string
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * Generated from protobuf field <code>string data = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkString($var, True);
        $this->data = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.courseadmin.codeData codedata = 4;</code>
     * @return \Courseadmin\codeData
     */
    public function getCodedata()
    {
        return $this->codedata;
    }

    /**
     * Generated from protobuf field <code>.courseadmin.codeData codedata = 4;</code>
     * @param \Courseadmin\codeData $var
     * @return $this
     */
    public function setCodedata($var)
    {
        GPBUtil::checkMessage($var, \Courseadmin\codeData::class);
        $this->codedata = $var;

        return $this;
    }

}

