<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: share.proto

namespace Share;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>share.shareRequest</code>
 */
class shareRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.share.Share share = 1;</code>
     */
    private $share = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Share\Share $share
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Share::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.share.Share share = 1;</code>
     * @return \Share\Share
     */
    public function getShare()
    {
        return $this->share;
    }

    /**
     * Generated from protobuf field <code>.share.Share share = 1;</code>
     * @param \Share\Share $var
     * @return $this
     */
    public function setShare($var)
    {
        GPBUtil::checkMessage($var, \Share\Share::class);
        $this->share = $var;

        return $this;
    }

}

